const tarotDeck = [
  // Major Arcana
  { name: 'The Fool', meaning: 'New beginnings, innocence', image: '/images/fool.jpg' },
  { name: 'The Magician', meaning: 'Manifestation, resourcefulness', image: '/images/magician.jpg' },
  { name: 'The High Priestess', meaning: 'Intuition, unconscious', image: '/images/highpriestess.jpg' },
  { name: 'The Empress', meaning: 'Fertility, nurturing', image: '/images/empress.jpg' },
  { name: 'The Emperor', meaning: 'Authority, structure', image: '/images/emperor.jpg' },
  { name: 'The Hierophant', meaning: 'Tradition, spirituality', image: '/images/hierophant.jpg' },
  { name: 'The Lovers', meaning: 'Love, partnership', image: '/images/lovers.jpg' },
  { name: 'The Chariot', meaning: 'Willpower, control', image: '/images/chariot.jpg' },
  { name: 'Strength', meaning: 'Courage, confidence', image: '/images/strength.jpg' },
  { name: 'The Hermit', meaning: 'Soul-searching, introspection', image: '/images/hermit.jpg' },
  { name: 'Wheel of Fortune', meaning: 'Change, cycles', image: '/images/wheeloffortune.jpg' },
  { name: 'Justice', meaning: 'Fairness, truth', image: '/images/justice.jpg' },
  { name: 'The Hanged Man', meaning: 'Surrender, new perspective', image: '/images/hangedman.jpg' },
  { name: 'Death', meaning: 'Endings, transformation', image: '/images/death.jpg' },
  { name: 'Temperance', meaning: 'Balance, moderation', image: '/images/temperance.jpg' },
  { name: 'The Devil', meaning: 'Addiction, materialism', image: '/images/devil.jpg' },
  { name: 'The Tower', meaning: 'Sudden upheaval, destruction', image: '/images/tower.jpg' },
  { name: 'The Star', meaning: 'Hope, inspiration', image: '/images/star.jpg' },
  { name: 'The Moon', meaning: 'Illusion, fear', image: '/images/moon.jpg' },
  { name: 'The Sun', meaning: 'Success, vitality', image: '/images/sun.jpg' },
  { name: 'Judgement', meaning: 'Rebirth, inner calling', image: '/images/judgement.jpg' },
  { name: 'The World', meaning: 'Completion, integration', image: '/images/world.jpg' },

  // Wands (Minor Arcana)
  { name: 'Ace of Wands', meaning: 'New opportunities, growth', image: '/images/acewands.jpg' },
  { name: 'Two of Wands', meaning: 'Future planning, decisions', image: '/images/2wands.jpg' },
  { name: 'Three of Wands', meaning: 'Expansion, growth', image: '/images/3wands.jpg' },
  { name: 'Four of Wands', meaning: 'Celebration, stability', image: '/images/4wands.jpg' },
  { name: 'Five of Wands', meaning: 'Conflict, competition', image: '/images/5wands.jpg' },
  { name: 'Six of Wands', meaning: 'Victory, success', image: '/images/6wands.jpg' },
  { name: 'Seven of Wands', meaning: 'Challenge, protection', image: '/images/7wands.jpg' },
  { name: 'Eight of Wands', meaning: 'Movement, fast-paced change', image: '/images/8wands.jpg' },
  { name: 'Nine of Wands', meaning: 'Resilience, perseverance', image: '/images/9wands.jpg' },
  { name: 'Ten of Wands', meaning: 'Burden, responsibility', image: '/images/10wands.jpg' },
  { name: 'Page of Wands', meaning: 'Exploration, discovery', image: '/images/pagewands.jpg' },
  { name: 'Knight of Wands', meaning: 'Action, adventure', image: '/images/knightwands.jpg' },
  { name: 'Queen of Wands', meaning: 'Courage, confidence', image: '/images/queenwands.jpg' },
  { name: 'King of Wands', meaning: 'Vision, leadership', image: '/images/kingwands.jpg' },

  // Cups (Minor Arcana)
  { name: 'Ace of Cups', meaning: 'New feelings, spirituality', image: '/images/acecups.jpg' },
  { name: 'Two of Cups', meaning: 'Partnership, connection', image: '/images/2cups.jpg' },
  { name: 'Three of Cups', meaning: 'Celebration, friendship', image: '/images/3cups.jpg' },
  { name: 'Four of Cups', meaning: 'Apathy, reevaluation', image: '/images/4cups.jpg' },
  { name: 'Five of Cups', meaning: 'Regret, loss', image: '/images/5cups.jpg' },
  { name: 'Six of Cups', meaning: 'Nostalgia, memories', image: '/images/6cups.jpg' },
  { name: 'Seven of Cups', meaning: 'Choices, illusion', image: '/images/7cups.jpg' },
  { name: 'Eight of Cups', meaning: 'Abandonment, withdrawal', image: '/images/8cups.jpg' },
  { name: 'Nine of Cups', meaning: 'Contentment, satisfaction', image: '/images/9cups.jpg' },
  { name: 'Ten of Cups', meaning: 'Happiness, fulfillment', image: '/images/10cups.jpg' },
  { name: 'Page of Cups', meaning: 'Creative opportunities, intuition', image: '/images/pagecups.jpg' },
  { name: 'Knight of Cups', meaning: 'Romance, charm', image: '/images/knightcups.jpg' },
  { name: 'Queen of Cups', meaning: 'Compassion, nurturing', image: '/images/queencups.jpg' },
  { name: 'King of Cups', meaning: 'Emotional balance, control', image: '/images/kingcups.jpg' },

  // Swords (Minor Arcana)
  { name: 'Ace of Swords', meaning: 'Breakthrough, clarity', image: '/images/aceswords.jpg' },
  { name: 'Two of Swords', meaning: 'Indecision, stalemate', image: '/images/2swords.jpg' },
  { name: 'Three of Swords', meaning: 'Heartbreak, sorrow', image: '/images/3swords.jpg' },
  { name: 'Four of Swords', meaning: 'Rest, recovery', image: '/images/4swords.jpg' },
  { name: 'Five of Swords', meaning: 'Conflict, defeat', image: '/images/5swords.jpg' },
  { name: 'Six of Swords', meaning: 'Transition, change', image: '/images/6swords.jpg' },
  { name: 'Seven of Swords', meaning: 'Deception, strategy', image: '/images/7swords.jpg' },
  { name: 'Eight of Swords', meaning: 'Imprisonment, restriction', image: '/images/8swords.jpg' },
  { name: 'Nine of Swords', meaning: 'Anxiety, fear', image: '/images/9swords.jpg' },
  { name: 'Ten of Swords', meaning: 'Betrayal, ending', image: '/images/10swords.jpg' },
  { name: 'Page of Swords', meaning: 'Curiosity, new ideas', image: '/images/pageswords.jpg' },
  { name: 'Knight of Swords', meaning: 'Ambition, action', image: '/images/knightswords.jpg' },
  { name: 'Queen of Swords', meaning: 'Perceptiveness, clarity', image: '/images/queenswords.jpg' },
  { name: 'King of Swords', meaning: 'Intellectual power, authority', image: '/images/kingswords.jpg' },

  // Pentacles (Minor Arcana)
  { name: 'Ace of Pentacles', meaning: 'New financial opportunity', image: '/images/acepentacles.jpg' },
  { name: 'Two of Pentacles', meaning: 'Balance, adaptability', image: '/images/2pentacles.jpg' },
  { name: 'Three of Pentacles', meaning: 'Teamwork, collaboration', image: '/images/3pentacles.jpg' },
  { name: 'Four of Pentacles', meaning: 'Conservation, control', image: '/images/4pentacles.jpg' },
  { name: 'Five of Pentacles', meaning: 'Financial loss, poverty', image: '/images/5pentacles.jpg' },
  { name: 'Six of Pentacles', meaning: 'Giving, receiving, generosity', image: '/images/6pentacles.jpg' },
  { name: 'Seven of Pentacles', meaning: 'Hard work, delayed success', image: '/images/7pentacles.jpg' },
  { name: 'Eight of Pentacles', meaning: 'Skill development, apprenticeship', image: '/images/8pentacles.jpg' },
  { name: 'Nine of Pentacles', meaning: 'Gratitude, luxury', image: '/images/9pentacles.jpg' },
  { name: 'Ten of Pentacles', meaning: 'Wealth, legacy', image: '/images/10pentacles.jpg' },
  { name: 'Page of Pentacles', meaning: 'Manifestation, financial opportunity', image: '/images/pagepentacles.jpg' },
  { name: 'Knight of Pentacles', meaning: 'Hard work, productivity', image: '/images/knightpentacles.jpg' },
  { name: 'Queen of Pentacles', meaning: 'Nurturing, practical', image: '/images/queenpentacles.jpg' },
  { name: 'King of Pentacles', meaning: 'Wealth, business leadership', image: '/images/kingpentacles.jpg' }
];

export default tarotDeck;
